# Generated by Django 3.0.3 on 2020-03-12 07:19

from django.db import migrations, models
import pipeline.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=10)),
                ('deps', models.CharField(max_length=1000)),
                ('file', models.FileField(upload_to=pipeline.models.get_upload_path)),
            ],
        ),
    ]
